### ISSUE TITLE
How do I rebuild the files 12S.mito.aln and 16S.mito.aln?

### ISSUE THREAD

**Issue by sjackman** [tseemann/barrnap#10]
I'm interested in building a plant mitochondrial database. Its rRNA are 5S, 18S and 26S
See #2

**Comment by tseemann** [comment]
Good question @sjackman 

What is the top-most level of the NCBI taxonomy that encompasses the "plant" family you are interested?

**Comment by sjackman** [comment]
Viridiplantae? I've been using this search:
```
esearch -db nuccore -query 'Viridiplantae[Organism] mitochondrion[Title] (complete genome[Title] OR complete sequence[Title])'
```
https://www.ncbi.nlm.nih.gov/nuccore/?term=Viridiplantae%5BOrganism%5D%20mitochondrion%5BTitle%5D%20(complete%20genome%5BTitle%5D%20OR%20complete%20sequence%5BTitle%5D)

**Comment by sjackman** [comment]
RFAM has alignments of rrn5, rrnS, and rrnL
Here are the RFAM bacterial family and clans for rrnS and rrnL. The clans include the families for other kingdoms. The bacterial families identify plant mitochondrion rrnS and rrnL.

5S_rRNA (RF00001) http://rfam.xfam.org/family/RF00001
5S_rRNA (CL00113) http://rfam.xfam.org/clan/CL00113

SSU_rRNA_bacteria (RF00177) http://rfam.org/family/RF00177
SSU (CL00111) http://rfam.org/clan/CL00111

LSU_rRNA_bacteria (RF02541) http://rfam.org/family/RF02541
LSU (CL00112) http://rfam.org/clan/CL00112

See https://github.com/tseemann/barrnap/issues/2#issuecomment-453600942
