### ISSUE TITLE
/nhmmer: Syntax error: ")" unexpected in barranp-0.7

### ISSUE THREAD

**Issue by MaggieLoT** [tseemann/barrnap#11]
Hello,
I just started using PROKKA and want to predict rRNA with barrnap-0.7. However, I'm getting the
following error while running it (on test example):
"/nhmmer: Syntax error: ")" unexpected"
What could be the issue here? Could it be the architecture of my system (I have 32-bit machine).
It also gave me the same error while running barrnap-0.6. 
Any solutions? 
Thank you very much,
MR

**Comment by tseemann** [comment]
I've updated to 0.8 version which might resolve this problem.
