### ISSUE TITLE
Feature request: allow input from stdin

### ISSUE THREAD

**Issue by mdehollander** [tseemann/barrnap#15]
This would make it easier to pipe gzipped data to barrnap

**Comment by tseemann** [comment]
This would be neat, but `nhmmer` doesn't support `stdin` (wants to `fseek()` for some reason) so I would need to make a temporary copy of the input.

**Comment by tseemann** [comment]
Good idea anyway, I have added support for STDIN.

**Comment by mdehollander** [comment]
Thanks!
