### ISSUE TITLE
Silva 123 up to date !!!

### ISSUE THREAD

**Issue by davidvilanova** [tseemann/barrnap#16]
Great,
Works well !!!!! 

Just have updated the database in file build_HMMs.sh to work with latest Silva 123  as follows. Replace with following chunk.

**SILVA="SILVA_123_LSURef_tax_silva_full_align_trunc.fasta"**
if [ ! -r "$SILVA" ]; then
  echo "Downloading: $SILVA"
  wget --quiet http://www.arb-silva.de/fileadmin/silva_databases/current/Exports/SILVA_123_LSURef_tax_silva_full_align_trunc.fasta.gz
  gunzip $SILVA.gz
  rm -f $SILVA.gz
else
  echo "Using existing file: $SILVA"
fi

thanks

**Comment by tseemann** [comment]
@davidvilanova thanks for the update -  I'm fixing the script now, and configuring for SILVA 128.

**Comment by tseemann** [comment]
You can now update to Barrnap 0.8
