### ISSUE TITLE
Concatenating all .hmm for a "meta" search?

### ISSUE THREAD

**Issue by bachev** [tseemann/barrnap#23]
Hi Torsten,

would it make sense to concatenate all db/*.hmm files to allow for a "meta" search?

Rationale: I have some eukaryotic RNASeq data and there one has rRNA from the cell as well as from the mitochondrion. And I would very much like not run barrnap twice (or more times for metagenomics) and then try to weed out by hand (i.e., by script) the most appropriate matches.

Best,
  B.

**Comment by tseemann** [comment]
@bachev that's a good question.

A simple concatenation will not work, as each kingdom shares *some* RNA subunits with others, but i've made kingdom-specific models for them. They have the same `NAME` in the `.hmm` files. So I would need to make kingdom part of the name to disambiguate them.

Secondly, I might have to be smarter how to select and filter competing matches.

I am looking into it.

**Comment by tseemann** [comment]
This is same as earlier #4 so I'll close this for now.
