### ISSUE TITLE
Typo in bedtools command breaks 0.9

### ISSUE THREAD

**Issue by kes1smmn** [tseemann/barrnap#29]
The current release fails on the `bedtools` command. it looks like #27 fixes the breaking typo.

**Comment by tseemann** [comment]
It's not a typo - you just have an older version of `bedtools`.   
But it seems to be affecting people so I'll look into it.

**Comment by kes1smmn** [comment]
I see.  You are correct I was using `bedtools<=2.26`.  Looks like `-name+` was added in the latest `bedtools==2.27`.

**Comment by tseemann** [comment]
I've updated the docs to say it needs 2.27.0 or higher.

**Comment by Rob-murphys** [comment]
This issue has appeared again. can it be made so that barrnap only install 2.27.0?
Weirdly this has only recently happened so for some reason when installing barrnap this week an older version of bedtools was installed with it.
