### ISSUE TITLE
minor doc typo on main README.md

### ISSUE THREAD

**Issue by jfass** [tseemann/barrnap#32]
the "Source" instructions for cloning the repo are missing the 'bin' directory when you run './barrnap --help' (if you follow the instructions explicitly you'll be in the directory above the bin directory, so that command won't run ... unless someone's added the barrnap bin dir to their path already)

**Comment by tseemann** [comment]
Thanks Joe - fixed in https://github.com/tseemann/barrnap/commit/acf3198a2e671f79107d8221bc32c110a6272ca6
