### ISSUE TITLE
Fasta file and GFF have shifted start of 16S

### ISSUE THREAD

**Issue by sleyn** [tseemann/barrnap#37]
Hello!

I'm using barrnap 0.9
Interesting observation that GFF file start positions are shifted by +1 compared to FASTA header start:

NC_009053	barrnap:0.9	rRNA	**69357**	70894	0	+	.	Name=16S_rRNA;product=16S ribosomal RNA

\>16S_rRNA::NC_009053:**69356**-70894(+)

Is this a bug or feature?

**Comment by tseemann** [comment]
@sleyn the problem occurs because BED files and GFF files use different coordinate systems. The FASTA file is generated by `bedtools` so it uses 0-based/end-exclusive while GFF uses 1-based/end-inclusive.

**Comment by sleyn** [comment]
Ok, thanks for explanation!
