### ISSUE TITLE
can barrnap-0.9 use hmmer/3.3

### ISSUE THREAD

**Issue by EricDeveaud** [tseemann/barrnap#41]
Hello 

barrnap/0.9 comes with bundle nhmmer from hmmer/3.3.1b1

can we use external nhmmer from version 3.3 instead ?

regards

Eric

**Comment by tseemann** [comment]
I didn't know 3.3 was released.
Are the databases compatible?
That would be the only thing stopping it from working.

**Comment by tseemann** [comment]
@EricDeveaud i just upgraded to nhmmer 3.3 and ran barrnap, it works fine.
